<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insert([
            ['id_producto'=>'P079','pro_descripcion'=>'Yogurt Natural','id_tipo'=>'HEL','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'INA','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'YogurtNatural.png'],
            ['id_producto'=>'P081','pro_descripcion'=>'Leche Descremada','id_tipo'=>'HEL','pro_um_compra'=>'CJ','pro_um_venta'=>'CJ','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'INA','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'LecheDescremada.png'],
            ['id_producto'=>'P080','pro_descripcion'=>'Yogurt de Fresa','id_tipo'=>'HEL','pro_um_compra'=>'DZA','pro_um_venta'=>'GL','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'YogurtdeFresa.png'],
            ['id_producto'=>'P082','pro_descripcion'=>'Leche Entera','id_tipo'=>'HEL','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.10,'pro_precio_venta'=>1.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'LecheEntera.png'],
            ['id_producto'=>'P083','pro_descripcion'=>'Queso Mozzarella','id_tipo'=>'HEL','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>4.50,'pro_precio_venta'=>5.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'QuesoMozzarella.png'],
            ['id_producto'=>'P084','pro_descripcion'=>'Mantequilla sin Sal','id_tipo'=>'HEL','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.00,'pro_precio_venta'=>3.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'MantequillasinSal.png'],
            ['id_producto'=>'P085','pro_descripcion'=>'Huevos','id_tipo'=>'HEL','pro_um_compra'=>'DZA','pro_um_venta'=>'DZA','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Huevos.png'],
            ['id_producto'=>'P086','pro_descripcion'=>'Pollo Entero','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.20,'pro_precio_venta'=>4.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'PolloEntero.png'],
            ['id_producto'=>'P087','pro_descripcion'=>'Frejol Carne Molida','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>4.00,'pro_precio_venta'=>5.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CarneMolida.png'],
            ['id_producto'=>'P088','pro_descripcion'=>'Chuleta de Cerdo','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>5.00,'pro_precio_venta'=>6.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'ChuletadeCerdo.png'],
            ['id_producto'=>'P089','pro_descripcion'=>'Café Instantáneo','id_tipo'=>'BEB','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>3.00,'pro_precio_venta'=>3.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CaféInstantáneo.png'],
            ['id_producto'=>'P090','pro_descripcion'=>'Bolsas de Plástico','id_tipo'=>'OTR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'BolsasdePlástico.png'],
            ['id_producto'=>'P091','pro_descripcion'=>'Miel de Abeja','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>4.50,'pro_precio_venta'=>5.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'MieldeAbeja.png'],
            ['id_producto'=>'P092','pro_descripcion'=>'Vinagre','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Vinagre.png'],
            ['id_producto'=>'P014','pro_descripcion'=>'Acondicionador','id_tipo'=>'OTR','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>3.20,'pro_precio_venta'=>0.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Acondicionador.png'],
            ['id_producto'=>'P015','pro_descripcion'=>'Cepillo Dental','id_tipo'=>'OTR','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CepilloDental.png'],
            ['id_producto'=>'P016','pro_descripcion'=>'Pasta Dental','id_tipo'=>'OTR','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>2.20,'pro_precio_venta'=>2.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'PastaDental.png'],
            ['id_producto'=>'P017','pro_descripcion'=>'Desinfectante','id_tipo'=>'OTR','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Desinfectante.png'],
            ['id_producto'=>'P018','pro_descripcion'=>'Cloro','id_tipo'=>'OTR','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Cloro.png'],
            ['id_producto'=>'P019','pro_descripcion'=>'Esponja de Cocina','id_tipo'=>'OTR','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>0.30,'pro_precio_venta'=>0.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'EsponjadeCocina.png'],
            ['id_producto'=>'P020','pro_descripcion'=>'Toalla de Papel','id_tipo'=>'OTR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>2.50,'pro_precio_venta'=>3.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'ToalladePapel.png'],

            ['id_producto'=>'P021','pro_descripcion'=>'Carne de Res','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>5.00,'pro_precio_venta'=>6.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CarnedeRes.png'],

            ['id_producto'=>'P022','pro_descripcion'=>'Pollo','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.50,'pro_precio_venta'=>4.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Pollo.png'],

            ['id_producto'=>'P023','pro_descripcion'=>'Pescado','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>4.50,'pro_precio_venta'=>5.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Pescado.png'],

            ['id_producto'=>'P024','pro_descripcion'=>'Queso','id_tipo'=>'HEL','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.20,'pro_precio_venta'=>4.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Queso.png'],

            ['id_producto'=>'P025','pro_descripcion'=>'Jamón','id_tipo'=>'CAR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>4.00,'pro_precio_venta'=>5.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Jamón.png'],

            ['id_producto'=>'P026','pro_descripcion'=>'Salchichas','id_tipo'=>'CAR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Salchichas.png'],

            ['id_producto'=>'P027','pro_descripcion'=>'Galletas Oreo','id_tipo'=>'GAL','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Galletas.png'],

            ['id_producto'=>'P028','pro_descripcion'=>'Pan de Molde','id_tipo'=>'GAL','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'PandeMolde.png'],

            ['id_producto'=>'P029','pro_descripcion'=>'Mantequilla','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.80,'pro_precio_venta'=>3.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Mantequilla.png'],

            ['id_producto'=>'P030','pro_descripcion'=>'Mayonesa','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Mayonesa.png'],

            ['id_producto'=>'P031','pro_descripcion'=>'Salsa de Tomate','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.50,'pro_precio_venta'=>1.90,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'SalsadeTomate.png'],

            ['id_producto'=>'P033','pro_descripcion'=>'Mermelada de Mora','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>2.20,'pro_precio_venta'=>2.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Mermelada.png'],

            ['id_producto'=>'P034','pro_descripcion'=>'Quinuavena','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.50,'pro_precio_venta'=>1.90,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Avena.png'],

            ['id_producto'=>'P035','pro_descripcion'=>'Sardinas','id_tipo'=>'CAR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Sardinas.png'],

            ['id_producto'=>'P036','pro_descripcion'=>'Atún','id_tipo'=>'CAR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Atun.png'],

            ['id_producto'=>'P037','pro_descripcion'=>'Jugo de Naranja','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'JugodeNaranja.png'],

            ['id_producto'=>'P038','pro_descripcion'=>'Refresco en Polvo','id_tipo'=>'BEB','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>0.90,'pro_precio_venta'=>1.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'RefrescoenPolvo.png'],

            ['id_producto'=>'P039','pro_descripcion'=>'Chocolate en Barra','id_tipo'=>'BEB','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>0.70,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'ChocolateenBarra.png'],

            ['id_producto'=>'P040','pro_descripcion'=>'Manteca','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Manteca.png'],

            ['id_producto'=>'P041','pro_descripcion'=>'Harina de Maíz','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.10,'pro_precio_venta'=>1.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'HarinadeMaíz.png'],

            ['id_producto'=>'P042','pro_descripcion'=>'Lentejas','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.30,'pro_precio_venta'=>1.70,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Lentejas.png'],

            ['id_producto'=>'P043','pro_descripcion'=>'Garbanzos','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.50,'pro_precio_venta'=>1.90,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Garbanzos.png'],

            ['id_producto'=>'P044','pro_descripcion'=>'Frijoles','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.40,'pro_precio_venta'=>1.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Frijoles.png'],

            ['id_producto'=>'P045','pro_descripcion'=>'Ajo','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.50,'pro_precio_venta'=>3.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Ajo.png'],

            ['id_producto'=>'P046','pro_descripcion'=>'Cebolla','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Cebolla.png'],

            ['id_producto'=>'P058','pro_descripcion'=>'Mango','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Mango.png'],

            ['id_producto'=>'P059','pro_descripcion'=>'Durazno','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.00,'pro_precio_venta'=>2.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Durazno.png'],

            ['id_producto'=>'P060','pro_descripcion'=>'Aguacate','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.50,'pro_precio_venta'=>3.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Aguacate.png'],

            ['id_producto'=>'P061','pro_descripcion'=>'Cerveza','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Cerveza.png'],

            ['id_producto'=>'P062','pro_descripcion'=>'Vino Tinto','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>5.00,'pro_precio_venta'=>7.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'VinoTinto.png'],

            ['id_producto'=>'P032','pro_descripcion'=>'Cereal','id_tipo'=>'GRN','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>3.00,'pro_precio_venta'=>3.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Cereal.png'],

            ['id_producto'=>'P063','pro_descripcion'=>'Vodka','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>8.00,'pro_precio_venta'=>10.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Vodka.png'],

            ['id_producto'=>'P064','pro_descripcion'=>'Ron','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>6.00,'pro_precio_venta'=>7.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Ron.png'],

            ['id_producto'=>'P001','pro_descripcion'=>'Arroz Blanco','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'ArrozBlanco.png'],

            ['id_producto'=>'P002','pro_descripcion'=>'Aceite','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>2.50,'pro_precio_venta'=>3.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'AceiteVegetal.png'],

            ['id_producto'=>'P093','pro_descripcion'=>'Bebida de Soja','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'SalsadeSoja.png'],

            ['id_producto'=>'P072','pro_descripcion'=>'Limonada','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'GaseosaLimón.png'],

            ['id_producto'=>'P073','pro_descripcion'=>'Cereal de Maíz','id_tipo'=>'GRN','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>2.50,'pro_precio_venta'=>3.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CerealdeMaíz.png'],

            ['id_producto'=>'P074','pro_descripcion'=>'Galletas de Chocolate','id_tipo'=>'GAL','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'GalletasdeChocolate.png'],

            ['id_producto'=>'P075','pro_descripcion'=>'Galletas de Vainilla','id_tipo'=>'GAL','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>1.30,'pro_precio_venta'=>1.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'GalletasdeVainilla.png'],

            ['id_producto'=>'P094','pro_descripcion'=>'Aceite de Oliva','id_tipo'=>'CON','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>5.00,'pro_precio_venta'=>6.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'AceitedeOliva.png'],

            ['id_producto'=>'P095','pro_descripcion'=>'Aceitunas','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.50,'pro_precio_venta'=>4.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Aceitunas.png'],

            ['id_producto'=>'P096','pro_descripcion'=>'Pepinillos','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.80,'pro_precio_venta'=>3.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Pepinillos.png'],

            ['id_producto'=>'P097','pro_descripcion'=>'Tortillas','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'HarinaparaTortillas.png'],

            ['id_producto'=>'P098','pro_descripcion'=>'Azúcar Morena','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.10,'pro_precio_venta'=>1.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'AzúcarMorena.png'],

            ['id_producto'=>'P099','pro_descripcion'=>'Chocolate en Polvo','id_tipo'=>'BEB','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>2.00,'pro_precio_venta'=>2.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'ChocolateenPolvo.png'],

            ['id_producto'=>'P100','pro_descripcion'=>'Gelatina','id_tipo'=>'BEB','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Gelatina.png'],

            ['id_producto'=>'P052','pro_descripcion'=>'Banano','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Banano.png'],

            ['id_producto'=>'P053','pro_descripcion'=>'Naranja','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.10,'pro_precio_venta'=>1.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Naranja.png'],

            ['id_producto'=>'P0999','pro_descripcion'=>'Limpia Vidrios','id_tipo'=>'OTR','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>0.00,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>null,'fecha_alta'=>'2025-10-01 15:27:34.408247','fecha_baja'=>null,'img'=>'LimpiaVidrios.png'],

            ['id_producto'=>'P054','pro_descripcion'=>'Limón','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Limón.png'],

            ['id_producto'=>'P055','pro_descripcion'=>'Piña','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.00,'pro_precio_venta'=>2.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Piña.png'],

            ['id_producto'=>'P056','pro_descripcion'=>'Sandía','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.50,'pro_precio_venta'=>1.90,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Sandía.png'],

            ['id_producto'=>'P057','pro_descripcion'=>'Uva','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.20,'pro_precio_venta'=>2.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Uva.png'],

            ['id_producto'=>'P065','pro_descripcion'=>'Whisky','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>15.00,'pro_precio_venta'=>18.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Whisky.png'],

            ['id_producto'=>'P066','pro_descripcion'=>'Tequila','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>12.00,'pro_precio_venta'=>15.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Tequila.png'],

            ['id_producto'=>'P067','pro_descripcion'=>'Coca Cola','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'CocaCola.png'],

            ['id_producto'=>'P068','pro_descripcion'=>'Pepsi','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Pepsi.png'],

            ['id_producto'=>'P069','pro_descripcion'=>'Jugo de Manzana','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.20,'pro_precio_venta'=>1.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'JugodeManzana.png'],

            ['id_producto'=>'P070','pro_descripcion'=>'Agua de Toronja','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>0.50,'pro_precio_venta'=>0.70,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'AguaToronja.png'],

            ['id_producto'=>'P071','pro_descripcion'=>'Gaseosa de Naranja','id_tipo'=>'BEB','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'GaseosaNaranja.png'],

            ['id_producto'=>'P047','pro_descripcion'=>'Pimiento','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.80,'pro_precio_venta'=>2.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Pimiento.png'],

            ['id_producto'=>'P048','pro_descripcion'=>'Zanahoria','id_tipo'=>'CON','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Zanahoria.png'],

            ['id_producto'=>'P049','pro_descripcion'=>'Papas fritas','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>0.90,'pro_precio_venta'=>1.10,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Papa.png'],

            ['id_producto'=>'P050','pro_descripcion'=>'Yuca','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Yuca.png'],

            ['id_producto'=>'P051','pro_descripcion'=>'Manzana','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.50,'pro_precio_venta'=>2.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Manzana.png'],

            ['id_producto'=>'P003','pro_descripcion'=>'Azúcar','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.10,'pro_precio_venta'=>1.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Azucar.png'],

            ['id_producto'=>'P004','pro_descripcion'=>'Leche en Polvo','id_tipo'=>'HEL','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>3.50,'pro_precio_venta'=>4.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'LecheenPolvo.png'],

            ['id_producto'=>'P005','pro_descripcion'=>'Fideos','id_tipo'=>'GRN','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>0.80,'pro_precio_venta'=>1.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Fideos.png'],

            ['id_producto'=>'P006','pro_descripcion'=>'Harina de Trigo','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>1.30,'pro_precio_venta'=>1.60,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'HarinadeTrigo.png'],

            ['id_producto'=>'P007','pro_descripcion'=>'Café','id_tipo'=>'BEB','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>2.00,'pro_precio_venta'=>2.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Cafe.png'],

            ['id_producto'=>'P008','pro_descripcion'=>'Sal','id_tipo'=>'GRN','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>0.50,'pro_precio_venta'=>0.70,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'Sal.png'],

            ['id_producto'=>'P009','pro_descripcion'=>'Leche Entera La Vaquita','id_tipo'=>'HEL','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>1.00,'pro_precio_venta'=>1.30,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'LecheEnteraLaVaquita.png'],

            ['id_producto'=>'P010','pro_descripcion'=>'Detergente en Polvo','id_tipo'=>'OTR','pro_um_compra'=>'KG','pro_um_venta'=>'KG','pro_valor_compra'=>2.80,'pro_precio_venta'=>3.40,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'DetergenteenPolvo.png'],

            ['id_producto'=>'P011','pro_descripcion'=>'Jabón de Tocador','id_tipo'=>'OTR','pro_um_compra'=>'UND','pro_um_venta'=>'UND','pro_valor_compra'=>0.40,'pro_precio_venta'=>0.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'JabóndeTocador.png'],

            ['id_producto'=>'P012','pro_descripcion'=>'Papel Higiénico','id_tipo'=>'OTR','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>2.00,'pro_precio_venta'=>2.50,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'PapelHigiénico.png'],

            ['id_producto'=>'P013','pro_descripcion'=>'Shampoo','id_tipo'=>'OTR','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>3.00,'pro_precio_venta'=>3.80,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'shampoo.jpeg'],

            ['id_producto'=>'P076','pro_descripcion'=>'Palomitas de Maíz','id_tipo'=>'GAL','pro_um_compra'=>'PK','pro_um_venta'=>'PK','pro_valor_compra'=>0.90,'pro_precio_venta'=>1.20,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'PalomitasdeMaíz.png'],

            ['id_producto'=>'P077','pro_descripcion'=>'Helado de Vainilla','id_tipo'=>'HEL','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>3.00,'pro_precio_venta'=>4.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'HeladodeVainilla.png'],
            ['id_producto'=>'P078','pro_descripcion'=>'Helado de Chocolate','id_tipo'=>'HEL','pro_um_compra'=>'LT','pro_um_venta'=>'LT','pro_valor_compra'=>3.00,'pro_precio_venta'=>4.00,'pro_saldo_inicial'=>300,'pro_qty_ingresos'=>0,'pro_qty_egresos'=>0,'pro_qty_ajustes'=>0,'pro_saldo_final'=>300,'estado_prod'=>'ACT','user_id'=>'root@localhost','fecha_alta'=>'2025-07-04 07:59:57','fecha_baja'=>null,'img'=>'HeladodeChocolate.png']


        ]);
        echo 'Seeder completo';
    }
}
